[workspace]
members = ["client", "common", "openapi", "server"]
resolver = "2"

[workspace.dependencies]
async-recursion = "1"
blake3 = { version = "1", features = ["mmap", "rayon"] }
bytesize = "2"
chrono = "0.4"
clap = { version = "4", features = ["derive", "env", "wrap_help"] }
crypto-bigint = "0.5"
dropshot = "0.16"
ed25519-dalek = { version = "2", features = ["rand_core"] }
function_name = "0.3"
futures = "0.3"
http = "1"
http-range-header = "0.4"
humantime = "2"
hyper = "1"
indicatif = "0.18"
libc = "0.2"
memmap2 = "0.9"
p256 = { version = "0.13", features = ["ecdsa"] }
pem-rfc7468 = { version = "0.7", features = ["std"] }
permission-slip-client = { git = "https://github.com/oxidecomputer/permission-slip" }
permission-slip-common = { git = "https://github.com/oxidecomputer/permission-slip" }
progenitor = "0.11"
rand = "0.8"
rand_core = "0.6"
reqwest = "0.12"
rlimit = "0.10"
rusqlite = { version = "0.37", features = ["blob", "chrono", "limits", "modern_sqlite", "rusqlite-macros"] }
rustyline = "17"
schemars = { version = "0.8", features = ["chrono", "preserve_order"] }
serde = "1"
serde_json = "1"
sha2 = "0.10"
shlex = "1"
slog = "2"
slog-term = "2"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["macros", "process", "rt", "sync", "time"] }
x509-cert = { version = "0.2", features = ["pem", "std"] }
xdg = "3"
