[package]
name = "sush-tests"
description = "Oxide Support Shell Integration Tests"
version.workspace = true
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/sush"
publish = false

[dependencies]
bytes.workspace = true
camino.workspace = true
chrono.workspace = true
dropshot.workspace = true
ed25519-dalek.workspace = true
function_name.workspace = true
futures.workspace = true
http-range-header.workspace = true
pwd.workspace = true
rand_core.workspace = true
rumors.workspace = true
sha3.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
slog-term.workspace = true
sprockets-tls.workspace = true
sprockets-tls-test-utils.workspace = true
sush-api = { path = "../api" }
sush-client = { path = "../client" }
sush-common = { path = "../common" }
sush-server = { path = "../server", features = ["test-support"] }
tempfile.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-util.workspace = true
x509-cert.workspace = true
