[package]
name = "sush-server"
description = "Oxide Support Shell Server"
version.workspace = true
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/sush"
publish = false

[[bin]]
name = "sush-server"
path = "src/main.rs"

[features]
embedded = []
test-support = []

[dependencies]
borsh.workspace = true
bytes.workspace = true
camino.workspace = true
bytesize.workspace = true
chrono.workspace = true
async-trait.workspace = true
clap.workspace = true
dropshot.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
http.workspace = true
http-body-util.workspace = true
http-range-header.workspace = true
hyper.workspace = true
hyper-util.workspace = true
libc.workspace = true
lru.workspace = true
memmap2.workspace = true
p256.workspace = true
percent-encoding.workspace = true
pwd.workspace = true
qorb.workspace = true
rumors.workspace = true
rand_core.workspace = true
rustix.workspace = true
rustls.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
slog-term.workspace = true
sprockets-tls.workspace = true
ssh-key.workspace = true
sush-api = { path = "../api" }
sush-common = { path = "../common" }
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio-tungstenite.workspace = true
uuid.workspace = true
x509-cert.workspace = true

[dev-dependencies]
attest-mock.workspace = true
function_name.workspace = true
rumors = { workspace = true, features = ["conformance"] }
sprockets-tls-test-utils.workspace = true
