[package]
name = "sush-server"
description = "Oxide Support Shell Server"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "sush-server"
path = "src/main.rs"

[dependencies]
blake3.workspace = true
bytes.workspace = true
bytesize.workspace = true
chrono.workspace = true
clap.workspace = true
dropshot.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
http-range-header.workspace = true
hyper.workspace = true
libc.workspace = true
lru.workspace = true
memmap2.workspace = true
p256.workspace = true
pwd.workspace = true
rand_core.workspace = true
rustix.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
slog.workspace = true
slog-term.workspace = true
ssh-key.workspace = true
sush-api = { path = "../api" }
sush-common = { path = "../common" }
tempfile.workspace = true
terminfo.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
uuid.workspace = true
x509-cert.workspace = true

[dev-dependencies]
function_name.workspace = true
