[package]
name = "sush-common"
description = "Oxide Support Shell Common Code"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
blake3.workspace = true
bytes.workspace = true
bytesize.workspace = true
chrono.workspace = true
crypto-bigint.workspace = true
ed25519-dalek.workspace = true
http-range-header.workspace = true
http.workspace = true
kms-agent.workspace = true
p256.workspace = true
pem-rfc7468.workspace = true
rand.workspace = true
rand_core.workspace = true
rlimit.workspace = true
rustix.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
signature.workspace = true
ssh-key.workspace = true
rusqlite.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
x509-cert.workspace = true
