//! SSH public key based authentication.
//!
//! We use HTTP authentication: the client makes a request, and the server
//! answers `401 (Unauthorized)` with a `WWW-Authenticate` challenge that
//! includes a fresh nonce. The client then chooses their own nonce, asks
//! their local SSH agent for a signature over both, and presents these all
//! as credentials in the `Authorization` header of a new request.
//!
//! This is not a standard HTTP authentication scheme, but we stick with a
//! simplified (no quoting) version of the usual `Scheme param=value, ...`
//! header encoding. A complete credential looks like this (newlines added
//! for readability):
//! ```text
//! Sush nonce=butter-such-draft-strategy-excess-road-grid-sample,
//!      cnonce=kick-tent-leaf-toast-write-inch-true-vanish,
//!      key-id=identify-joke-veteran-hair-pony-enact-vacuum-trumpet,
//!      r=absent-pulp-move-oyster-bench-catalog-exact-mixed-suggest-kid-unusual-board-govern-beef-unique-interest-antenna-view-obtain-addict-goat-insect-sponsor-peace,
//!      s=upon-slogan-super-dawn-autumn-artwork-settle-glimpse-margin-armor-away-solve-action-job-another-hidden-clay-slim-attend-sentence-august-churn-rigid,
//!      flags=1,
//!      counter=585
//! ```

use std::collections::HashMap;
use std::fmt;
use std::str::FromStr;

use blake3::Hasher;
use chrono::{DateTime, Utc};
use http::header::{HeaderValue, InvalidHeaderValue};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::codephrases::generate_id;
use crate::keys::{EncodedSignature, KeyError, KeyId, Signed, SshPublicKey, ToBeSigned, Verified};

/// The name of our custom HTTP authentication scheme.
pub const AUTHN_SCHEME: &str = "Sush";

/// The time-to-live of an identity, in seconds. Should be on the order
/// of minutes, but may not be reliable due to system time changes.
pub const IDENTITY_TTL: i64 = 600;

/// The time-to-live of a nonce, in seconds. Note that nonces do not
/// carry their own timestamps.
pub const NONCE_TTL: i64 = 60;

/// A unique random string. Authentication credentials have two
/// of these: one generated by the server, and one by the client.
/// This structure is agnostic to the syntax of the string.
#[derive(Clone, Debug, Deserialize, Eq, Hash, JsonSchema, PartialEq, Serialize)]
pub struct Nonce(String);

impl Nonce {
    pub fn generate() -> Self {
        Self(generate_id())
    }

    pub fn as_bytes(&self) -> &[u8] {
        self.0.as_bytes()
    }

    pub fn is_still_valid(time_generated: &DateTime<Utc>, now: &DateTime<Utc>) -> bool {
        (0..NONCE_TTL).contains(&now.signed_duration_since(time_generated).num_seconds())
    }
}

impl From<String> for Nonce {
    fn from(nonce: String) -> Self {
        Self(nonce)
    }
}

impl fmt::Display for Nonce {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Authentication challenge.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Challenge {
    nonce: Nonce,
}

impl Challenge {
    pub fn new(nonce: Nonce) -> Self {
        Self { nonce }
    }
}

impl fmt::Display for Challenge {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let Self { nonce } = self;
        write!(f, "{AUTHN_SCHEME} nonce={nonce}")
    }
}

impl TryFrom<Challenge> for HeaderValue {
    type Error = InvalidHeaderValue;

    fn try_from(challenge: Challenge) -> Result<Self, Self::Error> {
        HeaderValue::from_str(&challenge.to_string())
    }
}

impl FromStr for Challenge {
    type Err = AuthnError;

    /// Parse a server challenge, e.g., `Sush nonce=foo-bar-baz`.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut params = AuthnParams::from_str(s)?;
        let nonce = params.get("nonce")?;
        params.finished()?;
        Ok(Self::new(Nonce(nonce)))
    }
}

/// Response to an authentication challenge, containing the server-chosen
/// nonce and a fresh client-chosen nonce. This is the structure that is
/// signed and verified as authentication credentials.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ChallengeResponse {
    nonce: Nonce,
    cnonce: Nonce,
}

impl ChallengeResponse {
    const TYPE_NAME: &[u8] = b"sush_common::authn::ChallengeResponse";

    pub fn new(challenge: Challenge) -> Self {
        Self {
            nonce: challenge.nonce,
            cnonce: Nonce::generate(),
        }
    }
}

impl ToBeSigned for ChallengeResponse {
    /// BLAKE3 hash over the nonces.
    fn to_be_signed(&self) -> Vec<u8> {
        let mut hasher = Hasher::new();
        let mut hash = |data: &[u8]| {
            hasher.update(&(data.len() as u64).to_be_bytes());
            hasher.update(data);
        };

        let Self { nonce, cnonce } = self;
        hash(Self::TYPE_NAME);
        hash(nonce.as_bytes());
        hash(cnonce.as_bytes());
        hasher.finalize().as_bytes().to_vec()
    }
}

/// Authentication credentials presented to the server.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Credentials {
    /// Server-chosen nonce.
    pub nonce: Nonce,

    /// Client-chosen nonce.
    pub cnonce: Nonce,

    /// Key ID of the purported identity. The public key it identifies
    /// must already be known to the server.
    pub key_id: KeyId,

    /// Signature over `nonce` and `cnonce` by the private key of the
    /// purported identity.
    pub signature: EncodedSignature,
}

impl Credentials {
    /// The client must verify its own response before sending it
    /// to the server.
    pub fn new(verified: Verified<ChallengeResponse>) -> Self {
        let signature = verified.signature().to_owned();
        let key_id = verified.key_id().to_owned();
        let ChallengeResponse { nonce, cnonce } = verified.into_payload();
        Self {
            nonce,
            cnonce,
            key_id,
            signature,
        }
    }

    /// The server will parse the client's credentials and then use this
    /// method to begin verification.
    pub fn into_challenge_response(self) -> Signed<ChallengeResponse> {
        let Self {
            nonce,
            cnonce,
            key_id,
            signature,
        } = self;
        Signed::new(ChallengeResponse { nonce, cnonce }, key_id, signature)
    }
}

impl fmt::Display for Credentials {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let Self {
            nonce,
            cnonce,
            key_id,
            signature:
                EncodedSignature {
                    r,
                    s,
                    flags,
                    counter,
                },
        } = self;
        write!(
            f,
            "{AUTHN_SCHEME} \
             nonce={nonce}, cnonce={cnonce}, key-id={key_id}, \
             r={r}, s={s}, flags={flags}, counter={counter}",
        )
    }
}

impl FromStr for Credentials {
    type Err = AuthnError;

    /// Parse client credentials, e.g., `Sush nonce=foo-bar-baz, cnonce=qux-quux-quuux, ...`.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut params = AuthnParams::from_str(s)?;
        let creds = Self {
            nonce: params.get("nonce")?,
            cnonce: params.get("cnonce")?,
            key_id: params.get("key-id")?,
            signature: EncodedSignature {
                r: params.get("r")?,
                s: params.get("s")?,
                flags: params.parse("flags")?,
                counter: params.parse("counter")?,
            },
        };
        params.finished()?;
        Ok(creds)
    }
}

/// An authenticated identity.
#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
pub struct Identity {
    pub key_id: KeyId,
    pub public_key: SshPublicKey,
    pub nonce: Nonce,
    pub time_authenticated: DateTime<Utc>,
    pub time_revoked: Option<DateTime<Utc>>,
}

impl Identity {
    pub fn new(
        public_key: SshPublicKey,
        response: Verified<ChallengeResponse>,
        time_authenticated: DateTime<Utc>,
    ) -> Result<Self, KeyError> {
        let ChallengeResponse { nonce, cnonce: _ } = response.into_payload();
        Ok(Self {
            key_id: public_key.key_id()?,
            public_key,
            nonce,
            time_authenticated,
            time_revoked: None,
        })
    }

    pub fn is_still_valid(&self, now: &DateTime<Utc>) -> bool {
        self.time_revoked.is_none()
            && (0..IDENTITY_TTL).contains(
                &now.signed_duration_since(self.time_authenticated)
                    .num_seconds(),
            )
    }
}

/// Helper for parsing `WWW-Authenticate` and `Authorization` headers
/// comprised of a scheme and parameter name/value pairs.
struct AuthnParams(HashMap<String, String>);

impl AuthnParams {
    /// Consume and cast one parameter.
    fn get<T: From<String>>(&mut self, param: &'static str) -> Result<T, AuthnError> {
        self.0
            .remove(param)
            .map(|value| value.into())
            .ok_or(AuthnError::MissingParam(param))
    }

    /// Consume and parse one parameter.
    fn parse<T: FromStr>(&mut self, param: &'static str) -> Result<T, AuthnError> {
        self.get::<String>(param)?
            .parse()
            .map_err(|_| AuthnError::InvalidParam)
    }

    /// Ensure that all parameters have been consumed.
    fn finished(self) -> Result<(), AuthnError> {
        if self.0.is_empty() {
            Ok(())
        } else {
            Err(AuthnError::TooManyParams)
        }
    }
}

impl FromStr for AuthnParams {
    type Err = AuthnError;

    /// Parse a header value of the form `Scheme name=value, ...`
    /// and build a map of `(name, value)` pairs. Quoting is not
    /// currently supported; names and values should all be free
    /// of whitespace, commas, and equals signs.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let Some((scheme, rest)) = s.split_once(" ") else {
            return Err(AuthnError::MissingScheme);
        };
        if !scheme.trim().eq_ignore_ascii_case(AUTHN_SCHEME) {
            return Err(AuthnError::InvalidScheme(scheme.to_string()));
        }

        let mut params = HashMap::new();
        for param in rest.split(",") {
            let Some((name, value)) = param.split_once("=") else {
                return Err(AuthnError::InvalidParam);
            };
            let name = name.trim().to_ascii_lowercase();
            if params.contains_key(&name) {
                return Err(AuthnError::DuplicateParam(name));
            }
            params.insert(name, value.trim().to_string());
        }
        Ok(Self(params))
    }
}

/// What went wrong during authentication.
#[derive(Debug, Error)]
pub enum AuthnError {
    #[error("Duplicate authentication parameter `{0}")]
    DuplicateParam(String),
    #[error("Invalid authentication parameter")]
    InvalidParam,
    #[error("Invalid authentication scheme `{0}`")]
    InvalidScheme(String),
    #[error("Missing credential parameter `{0}`")]
    MissingParam(&'static str),
    #[error("Invalid signature counter")]
    InvalidSignatureCounter,
    #[error("Invalid signature flags")]
    InvalidSignatureFlags,
    #[error("Missing authentication scheme")]
    MissingScheme,
    #[error("Too many credential parameters")]
    TooManyParams,
}

#[cfg(test)]
mod test {
    use std::time::Duration;
    use x509_cert::name::Name;
    use x509_cert::time::Validity;

    use crate::keys::{EphemeralKey, KeyType, Signer as _};

    use super::*;

    #[tokio::test]
    async fn challenge_response() {
        let name = "CN=Ephemeral Authenticator,O=Oxide Computer Company,C=US"
            .parse::<Name>()
            .unwrap();
        let validity = Validity::from_now(Duration::from_secs(60)).unwrap();
        let mut signer = EphemeralKey::new_root(KeyType::Ed25519, name, validity).unwrap();
        for _ in 0..10 {
            let key_id = signer.key_id().clone();
            let nonce = Nonce::generate();
            let challenge = Challenge::new(nonce.clone());
            let www_authenticate = challenge.to_string();
            assert_eq!(www_authenticate, format!("Sush nonce={nonce}"));
            assert_eq!(challenge, Challenge::from_str(&www_authenticate).unwrap());

            let response = ChallengeResponse::new(challenge);
            let cnonce = response.cnonce.clone();
            let tbs = response.to_be_signed();
            assert_eq!(tbs.len(), 32);
            let signed = signer.sign(tbs.clone()).await.unwrap();
            let signature = signed.signature().clone();
            let verified = signed.verify_with_cert(signer.cert()).unwrap();
            assert_eq!(verified.key_id(), &key_id);
            assert_eq!(verified.into_payload(), tbs);

            let signed = signer.sign(response).await.unwrap();
            let verified = signed.verify_with_cert(signer.cert()).unwrap();
            let credentials = Credentials::new(verified);
            let EncodedSignature {
                r,
                s,
                flags,
                counter,
            } = &signature;
            assert_eq!(
                credentials.to_string(),
                format!(
                    "Sush nonce={nonce}, cnonce={cnonce}, key-id={key_id}, r={r}, s={s}, flags={flags}, counter={counter}"
                )
            );
            assert_eq!(
                credentials.to_string().parse::<Credentials>().unwrap(),
                credentials
            );
            assert_eq!(
                credentials,
                Credentials {
                    nonce,
                    cnonce,
                    key_id,
                    signature
                }
            );
        }
    }

    #[test]
    fn authn_errors() {
        assert!(matches!(
            Credentials::from_str("").unwrap_err(),
            AuthnError::MissingScheme
        ));
        assert!(matches!(
            Credentials::from_str("Foo foo").unwrap_err(),
            AuthnError::InvalidScheme(scheme) if scheme == "Foo"
        ));
        assert!(matches!(
            Credentials::from_str("Sush foo").unwrap_err(),
            AuthnError::InvalidParam
        ));
        assert!(matches!(
            Credentials::from_str("Sush x=y,z").unwrap_err(),
            AuthnError::InvalidParam
        ));
        assert!(matches!(
            Credentials::from_str("Sush x=y,x=z").unwrap_err(),
            AuthnError::DuplicateParam(p) if p == "x"
        ));
        assert!(matches!(
            Credentials::from_str("Sush x=y").unwrap_err(),
            AuthnError::MissingParam(p) if p == "nonce"
        ));
        assert!(matches!(
            Credentials::from_str("Sush nonce=foo").unwrap_err(),
            AuthnError::MissingParam(p) if p == "cnonce"
        ));
        assert!(matches!(
            Credentials::from_str(
                "Sush nonce=foo,cnonce=bar,key-id=baz,r=r,s=s,flags=0,counter=foo"
            )
            .unwrap_err(),
            AuthnError::InvalidParam
        ));
        assert!(matches!(
            Credentials::from_str(
                "Sush nonce=foo,cnonce=bar,key-id=baz,r=r,s=s,flags=0,counter=0,foo=bar"
            )
            .unwrap_err(),
            AuthnError::TooManyParams
        ));
    }
}
