// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! SSH public key based authentication.
//!
//! We use HTTP authentication: the client makes a request, and the server
//! answers `401 (Unauthorized)` with a `WWW-Authenticate` challenge that
//! includes a fresh nonce. The client then chooses their own nonce, asks
//! their local SSH agent for a signature over both, and presents these all
//! as credentials in the `Authorization` header of a new request.
//!
//! This is not a standard HTTP authentication scheme, but we stick with a
//! simplified (no quoting) version of the usual `Scheme param=value, ...`
//! header encoding. A complete credential looks like this (newlines added
//! for readability):
//! ```text
//! Sush nonce=butter-such-draft-strategy-excess-road-grid-sample,
//!      cnonce=kick-tent-leaf-toast-write-inch-true-vanish,
//!      key-id=identify-joke-veteran-hair-pony-enact-vacuum-trumpet,
//!      r=absent-pulp-move-oyster-bench-catalog-exact-mixed-suggest-kid-unusual-board-govern-beef-unique-interest-antenna-view-obtain-addict-goat-insect-sponsor-peace,
//!      s=upon-slogan-super-dawn-autumn-artwork-settle-glimpse-margin-armor-away-solve-action-job-another-hidden-clay-slim-attend-sentence-august-churn-rigid,
//!      flags=1,
//!      counter=585
//! ```

use std::collections::HashMap;
use std::fmt;
use std::str::FromStr;
use std::time::Duration;

use chrono::{DateTime, Utc};
use crypto_bigint::U256;
use ed25519_dalek::{Signature as Ed25519Signature, Signer as _, SigningKey, VerifyingKey};
use http::header::{HeaderValue, InvalidHeaderValue};
use rand_core::OsRng;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::codephrase_newtype;
use crate::codephrases::InvalidCodephrase;
use crate::keys::{
    EccR, EccS, EncodedSignature, KeyError, KeyId, Signed, SshPublicKey, ToBeSigned,
    ToBeSignedFields, Verified,
};

/// The name of our custom HTTP authentication scheme.
pub const AUTHN_SCHEME: &str = "Sush";

/// How long an identity may sit idle before it expires. Each verified
/// bound request restarts the clock.
///
/// All three lifetimes here are measured on the monotonic clock: sush
/// runs before NTP has synced, and a wall-clock step of decades must
/// not expire anyone.
pub const IDENTITY_IDLE_TTL: Duration = Duration::from_secs(600);

/// The absolute lifetime of an identity, however busy.
pub const IDENTITY_MAX_TTL: Duration = Duration::from_secs(8 * 3600);

/// The time-to-live of a nonce.
pub const NONCE_TTL: Duration = Duration::from_secs(60);

codephrase_newtype! {
    /// A unique random string. Authentication credentials have two
    /// of these: one generated by the server, and one by the client.
    /// This structure is agnostic to the syntax of the string.
    #[derive(
        Clone,
        Deserialize,
        Eq,
        Hash,
        JsonSchema,
        PartialEq,
        Serialize,
    )]
    pub struct Nonce = Truncated;
}

/// Authentication challenge.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Challenge {
    nonce: Nonce,
}

impl Challenge {
    pub fn new(nonce: Nonce) -> Self {
        Self { nonce }
    }
}

impl fmt::Display for Challenge {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let Self { nonce } = self;
        write!(f, "{AUTHN_SCHEME} nonce={nonce}")
    }
}

impl TryFrom<Challenge> for HeaderValue {
    type Error = InvalidHeaderValue;

    fn try_from(challenge: Challenge) -> Result<Self, Self::Error> {
        HeaderValue::from_str(&challenge.to_string())
    }
}

impl FromStr for Challenge {
    type Err = AuthnError;

    /// Parse a server challenge, e.g., `Sush nonce=foo-bar-baz`.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut params = AuthnParams::from_str(s)?;
        let nonce = params.parse("nonce")?;
        params.finished()?;
        Ok(Self::new(Nonce(nonce)))
    }
}

/// The client half of an ephemeral request-signing key, minted per
/// authentication. Its public half rides in the signed challenge
/// response, and it then signs every request without further use of
/// the identity key.
#[derive(Clone, Debug)]
pub struct RequestKey(SigningKey);

impl RequestKey {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        Self(SigningKey::generate(&mut OsRng))
    }

    pub fn verifier(&self) -> RequestVerifier {
        RequestVerifier::from_be_bytes(*self.0.verifying_key().as_bytes())
    }

    /// Sign `request`, yielding the credentials that authorize it.
    pub fn bind(&self, key_id: KeyId, nonce: Nonce, request: &BoundRequest) -> BoundCredentials {
        let signature = self.0.sign(&request.to_be_signed(&key_id, &nonce));
        BoundCredentials {
            key_id,
            nonce,
            seq: request.seq,
            signature: EncodedSignature {
                r: EccR::from_be_bytes(*signature.r_bytes()),
                s: EccS::from_be_bytes(*signature.s_bytes()),
                flags: 0,
                counter: 0,
            },
        }
    }
}

codephrase_newtype! {
    /// The server half of an ephemeral request-signing key.
    #[derive(Clone, Deserialize, Eq, PartialEq, Serialize)]
    pub struct RequestVerifier = Full;

}

impl RequestVerifier {
    /// Verify that `credentials` sign `request`.
    pub fn verify(
        &self,
        request: &BoundRequest,
        credentials: &BoundCredentials,
    ) -> Result<(), AuthnError> {
        if request.seq != credentials.seq {
            return Err(AuthnError::InvalidSignature);
        }
        let EncodedSignature { r, s, .. } = &credentials.signature;
        let signature = Ed25519Signature::from_components(r.to_be_bytes(), s.to_be_bytes());

        let key =
            VerifyingKey::from_bytes(&self.to_be_bytes()).map_err(|_| AuthnError::InvalidKey)?;
        // A small-order key verifies anything, degrading the session
        // back to a bearer credential.
        if key.is_weak() {
            return Err(AuthnError::InvalidKey);
        }

        key.verify_strict(
            &request.to_be_signed(&credentials.key_id, &credentials.nonce),
            &signature,
        )
        .map_err(|_| AuthnError::InvalidSignature)
    }
}

/// One request, as material to be signed. The target is the exact
/// request line's path and query, so client and server sign the same
/// bytes by construction. Bodies are excluded because every meaningful
/// body authenticates itself.
#[derive(Debug, Eq, PartialEq)]
pub struct BoundRequest {
    /// Uppercase HTTP method.
    pub method: String,
    /// The request target: path and query, exactly as sent.
    pub target: String,
    /// The request's unique, increasing sequence number.
    pub seq: u64,
}

impl BoundRequest {
    const TYPE_NAME: &[u8] = b"sush_common::authn::BoundRequest";

    pub fn new(method: &str, target: &str, seq: u64) -> Self {
        Self {
            method: method.to_ascii_uppercase(),
            target: target.to_string(),
            seq,
        }
    }

    /// Hash of the labeled components.
    fn to_be_signed(&self, key_id: &KeyId, nonce: &Nonce) -> Vec<u8> {
        let Self {
            method,
            target,
            seq,
        } = self;
        ToBeSignedFields::new(Self::TYPE_NAME)
            .field(b"key_id", &key_id.to_be_bytes())
            .field(b"nonce", &nonce.to_be_bytes())
            .field(b"method", method.as_bytes())
            .field(b"target", target.as_bytes())
            .field(b"seq", &seq.to_be_bytes())
            .finish()
    }
}

/// Credentials binding one request to an authenticated identity.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BoundCredentials {
    /// Key ID of the authenticated identity.
    pub key_id: KeyId,
    /// The server-chosen nonce from authentication.
    pub nonce: Nonce,
    /// The request's sequence number.
    pub seq: u64,
    /// Ephemeral signature over the request.
    pub signature: EncodedSignature,
}

impl fmt::Display for BoundCredentials {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let Self {
            key_id,
            nonce,
            seq,
            signature: EncodedSignature { r, s, .. },
        } = self;
        write!(
            f,
            "{AUTHN_SCHEME} key-id={key_id}, nonce={nonce}, seq={seq}, r={r}, s={s}",
        )
    }
}

impl FromStr for BoundCredentials {
    type Err = AuthnError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut params = AuthnParams::from_str(s)?;
        let creds = Self {
            key_id: params.parse("key-id")?,
            nonce: params.parse("nonce")?,
            seq: params.parse("seq")?,
            signature: EncodedSignature {
                r: params.parse("r")?,

                s: params.parse("s")?,
                flags: 0,
                counter: 0,
            },
        };
        params.finished()?;
        Ok(creds)
    }
}

/// An `Authorization` header: initial credentials authenticate at
/// `iam`, bound credentials authorize every other request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Authn {
    Initial(Box<Credentials>),
    Bound(BoundCredentials),
}

impl FromStr for Authn {
    type Err = AuthnError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if AuthnParams::from_str(s)?.has("seq") {
            Ok(Self::Bound(s.parse()?))
        } else {
            Ok(Self::Initial(Box::new(s.parse()?)))
        }
    }
}

/// How many sequence numbers a [`SeqWindow`] tracks. Must comfortably
/// exceed the client's maximum concurrency, or a straggling request
/// falls out of the window and fails.
pub const SEQ_WINDOW: u64 = 256;

/// The sequence numbers an identity has spent, tracked over the
/// [`SEQ_WINDOW`] values up to the highest seen. The window lets
/// concurrent requests arrive out of order without opening a replay.
/// Anything older is refused. Bit `age` of `seen` marks
/// `highest - age` as spent.
///
/// Each server keeps its own windows, so a captured request may be
/// replayed to a server that has not spent its sequence number yet.
/// State requests are deduplicated rack-wide by the state machine.
/// Requests served from local state (output reads, attaches) can be
/// re-issued to any sled their signed target resolves to.
#[derive(Clone, Copy, Debug, Default)]
pub struct SeqWindow {
    highest: u64,
    seen: U256,
}

impl SeqWindow {
    /// Spend `seq`, unless it was already spent or predates the window.
    pub fn spend(&mut self, seq: u64) -> bool {
        if seq > self.highest {
            let shift = seq - self.highest;
            self.seen = if shift < SEQ_WINDOW {
                self.seen.shl_vartime(shift as usize)
            } else {
                U256::ZERO
            };
            self.seen |= U256::ONE;
            self.highest = seq;
            return true;
        }
        let age = self.highest - seq;
        if age >= SEQ_WINDOW || self.seen.bit_vartime(age as usize) {
            return false;
        }
        self.seen |= U256::ONE.shl_vartime(age as usize);
        true
    }
}

/// Response to an authentication challenge, containing the server-chosen
/// nonce and a fresh client-chosen nonce. This is the structure that is
/// signed and verified as authentication credentials.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ChallengeResponse {
    nonce: Nonce,
    cnonce: Nonce,
    epk: RequestVerifier,
}

/// Signed authentication evidence, self-certifying to any verifier.
pub type SignedLogin = Signed<ChallengeResponse>;

impl ChallengeResponse {
    const TYPE_NAME: &[u8] = b"sush_common::authn::ChallengeResponse";

    pub fn new(challenge: Challenge, epk: RequestVerifier) -> Self {
        Self {
            nonce: challenge.nonce,
            cnonce: Nonce::random(),
            epk,
        }
    }

    pub fn epk(&self) -> &RequestVerifier {
        &self.epk
    }
}

impl ToBeSigned for ChallengeResponse {
    /// Hash of the labeled nonces and ephemeral key.
    fn to_be_signed(&self) -> Vec<u8> {
        let Self { nonce, cnonce, epk } = self;
        ToBeSignedFields::new(Self::TYPE_NAME)
            .field(b"nonce", &nonce.to_be_bytes())
            .field(b"cnonce", &cnonce.to_be_bytes())
            .field(b"epk", &epk.to_be_bytes())
            .finish()
    }
}

/// Authentication credentials presented to the server.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Credentials {
    /// Server-chosen nonce.
    pub nonce: Nonce,

    /// Client-chosen nonce.
    pub cnonce: Nonce,

    /// Key ID of the purported identity. The public key it identifies
    /// must already be known to the server.
    pub key_id: KeyId,

    /// Public half of the ephemeral key that will sign this
    /// identity's requests.
    pub epk: RequestVerifier,

    /// Signature over `nonce`, `cnonce`, and `epk` by the private key
    /// of the purported identity.
    pub signature: EncodedSignature,
}

impl Credentials {
    /// The client must verify its own response before sending it
    /// to the server.
    pub fn new(verified: Verified<ChallengeResponse>) -> Self {
        let signature = verified.signature().to_owned();
        let key_id = verified.key_id().to_owned();
        let ChallengeResponse { nonce, cnonce, epk } = verified.into_payload();
        Self {
            epk,
            nonce,
            cnonce,
            key_id,
            signature,
        }
    }

    /// The server will parse the client's credentials and then use this
    /// method to begin verification.
    pub fn into_challenge_response(self) -> Signed<ChallengeResponse> {
        let Self {
            nonce,
            cnonce,
            key_id,
            epk,
            signature,
        } = self;
        Signed::new(ChallengeResponse { nonce, cnonce, epk }, key_id, signature)
    }
}

impl fmt::Display for Credentials {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let Self {
            nonce,
            cnonce,
            key_id,
            epk,
            signature:
                EncodedSignature {
                    r,
                    s,
                    flags,
                    counter,
                },
        } = self;
        write!(
            f,
            "{AUTHN_SCHEME} \
             nonce={nonce}, cnonce={cnonce}, key-id={key_id}, epk={epk}, \
             r={r}, s={s}, flags={flags}, counter={counter}",
        )
    }
}

impl FromStr for Credentials {
    type Err = AuthnError;

    /// Parse client credentials, e.g., `Sush nonce=foo-bar-baz, cnonce=qux-quux-quuux, ...`.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut params = AuthnParams::from_str(s)?;
        let creds = Self {
            nonce: params.parse("nonce")?,
            cnonce: params.parse("cnonce")?,
            key_id: params.parse("key-id")?,
            epk: params.parse("epk")?,
            signature: EncodedSignature {
                r: params.parse("r")?,
                s: params.parse("s")?,
                flags: params.parse("flags")?,
                counter: params.parse("counter")?,
            },
        };
        params.finished()?;
        Ok(creds)
    }
}

/// An authenticated identity.
#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
pub struct Identity {
    pub key_id: KeyId,
    pub public_key: SshPublicKey,
    pub nonce: Nonce,
    pub time_authenticated: DateTime<Utc>,
    pub time_revoked: Option<DateTime<Utc>>,
}

impl Identity {
    pub fn new(
        public_key: SshPublicKey,
        response: Verified<ChallengeResponse>,
        time_authenticated: DateTime<Utc>,
    ) -> Result<Self, KeyError> {
        let key_id = public_key.key_id()?;
        if response.verified_by() != &key_id {
            return Err(KeyError::InvalidKeyId);
        }
        let ChallengeResponse { nonce, .. } = response.into_payload();
        Ok(Self {
            key_id,
            public_key,
            nonce,
            time_authenticated,
            time_revoked: None,
        })
    }
}

/// Helper for parsing `WWW-Authenticate` and `Authorization` headers
/// comprised of a scheme and parameter name/value pairs.
struct AuthnParams(HashMap<String, String>);

impl AuthnParams {
    /// Consume and cast one parameter.
    fn get<T: From<String>>(&mut self, param: &'static str) -> Result<T, AuthnError> {
        self.0
            .remove(param)
            .map(|value| value.into())
            .ok_or(AuthnError::MissingParam(param))
    }

    /// Consume and parse one parameter.
    fn parse<T: FromStr>(&mut self, param: &'static str) -> Result<T, AuthnError> {
        self.get::<String>(param)?
            .parse()
            .map_err(|_| AuthnError::InvalidParam)
    }

    /// Whether a parameter is present, without consuming it.
    fn has(&self, param: &str) -> bool {
        self.0.contains_key(param)
    }

    /// Ensure that all parameters have been consumed.
    fn finished(self) -> Result<(), AuthnError> {
        if self.0.is_empty() {
            Ok(())
        } else {
            Err(AuthnError::TooManyParams)
        }
    }
}

impl FromStr for AuthnParams {
    type Err = AuthnError;

    /// Parse a header value of the form `Scheme name=value, ...`
    /// and build a map of `(name, value)` pairs. Quoting is not
    /// currently supported; names and values should all be free
    /// of whitespace, commas, and equals signs.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let Some((scheme, rest)) = s.split_once(" ") else {
            return Err(AuthnError::MissingScheme);
        };
        if !scheme.trim().eq_ignore_ascii_case(AUTHN_SCHEME) {
            return Err(AuthnError::InvalidScheme(scheme.to_string()));
        }

        let mut params = HashMap::new();
        for param in rest.split(",") {
            let Some((name, value)) = param.split_once("=") else {
                return Err(AuthnError::InvalidParam);
            };
            let name = name.trim().to_ascii_lowercase();
            if params.contains_key(&name) {
                return Err(AuthnError::DuplicateParam(name));
            }
            params.insert(name, value.trim().to_string());
        }
        Ok(Self(params))
    }
}

/// What went wrong during authentication.
#[derive(Debug, Error)]
pub enum AuthnError {
    #[error(transparent)]
    Codephrase(#[from] InvalidCodephrase),
    #[error("Duplicate authentication parameter `{0}`")]
    DuplicateParam(String),
    #[error("Invalid ephemeral key")]
    InvalidKey,
    #[error("Invalid request signature")]
    InvalidSignature,
    #[error("Invalid authentication parameter")]
    InvalidParam,
    #[error("Invalid authentication scheme `{0}`")]
    InvalidScheme(String),
    #[error("Missing credential parameter `{0}`")]
    MissingParam(&'static str),
    #[error("Missing authentication scheme")]
    MissingScheme,
    #[error("Too many credential parameters")]
    TooManyParams,
}

#[cfg(test)]
mod test {
    use std::time::Duration;
    use x509_cert::name::Name;
    use x509_cert::time::Validity;

    use crate::keys::{EphemeralKey, KeyType, Signer as _};

    use super::*;

    #[tokio::test]
    async fn challenge_response() {
        let name = "CN=Ephemeral Authenticator,O=Oxide Computer Company,C=US"
            .parse::<Name>()
            .unwrap();
        let validity = Validity::from_now(Duration::from_secs(60)).unwrap();
        let mut signer = EphemeralKey::new_root(KeyType::Ed25519, name, validity).unwrap();
        for _ in 0..10 {
            let key_id = signer.key_id().clone();
            let nonce = Nonce::random();
            let challenge = Challenge::new(nonce.clone());
            let www_authenticate = challenge.to_string();
            assert_eq!(www_authenticate, format!("Sush nonce={nonce}"));
            assert_eq!(challenge, Challenge::from_str(&www_authenticate).unwrap());

            let key = RequestKey::new();
            let epk = key.verifier();
            let response = ChallengeResponse::new(challenge, epk.clone());
            let cnonce = response.cnonce.clone();
            let tbs = response.to_be_signed();
            assert_eq!(tbs.len(), 32);
            let signed = signer.sign(tbs.clone()).await.unwrap();
            let signature = signed.signature().clone();
            let verified = signed.verify_with_cert(signer.cert()).unwrap();
            assert_eq!(verified.key_id(), &key_id);
            assert_eq!(verified.into_payload(), tbs);

            let signed = signer.sign(response).await.unwrap();
            let verified = signed.verify_with_cert(signer.cert()).unwrap();
            let credentials = Credentials::new(verified);
            let EncodedSignature {
                r,
                s,
                flags,
                counter,
            } = &signature;
            assert_eq!(
                credentials.to_string(),
                format!(
                    "Sush nonce={nonce}, cnonce={cnonce}, key-id={key_id}, epk={epk}, r={r}, s={s}, flags={flags}, counter={counter}"
                )
            );
            assert_eq!(
                credentials.to_string().parse::<Credentials>().unwrap(),
                credentials
            );
            assert_eq!(
                credentials,
                Credentials {
                    nonce,
                    cnonce,
                    key_id,
                    epk,
                    signature
                }
            );
        }
    }

    #[test]
    fn bound_requests() {
        let key = RequestKey::new();
        let verifier = key.verifier();
        let request = BoundRequest::new("get", "/jobs?limit=1", 7);
        let creds = key.bind(
            KeyId::from_str("abandon").unwrap(),
            Nonce::random(),
            &request,
        );
        assert_eq!(
            creds.to_string().parse::<BoundCredentials>().unwrap(),
            creds
        );
        assert!(matches!(
            creds.to_string().parse::<Authn>().unwrap(),
            Authn::Bound(parsed) if parsed == creds
        ));

        // The method is signed case-insensitively. Everything else
        // must match exactly.
        verifier.verify(&request, &creds).unwrap();
        let verify =
            |method, target, seq| verifier.verify(&BoundRequest::new(method, target, seq), &creds);
        verify("GET", "/jobs?limit=1", 7).unwrap();
        assert!(verify("POST", "/jobs?limit=1", 7).is_err());
        assert!(verify("GET", "/jobs?limit=2", 7).is_err());
        assert!(verify("GET", "/jobs?limit=1", 8).is_err());
        assert!(
            RequestKey::new()
                .verifier()
                .verify(&request, &creds)
                .is_err()
        );

        // The identity is part of the signed material: credentials
        // re-labeled with another key ID or nonce do not verify.
        let relabeled = BoundCredentials {
            key_id: KeyId::from_str("ability").unwrap(),
            ..creds.clone()
        };
        assert!(verifier.verify(&request, &relabeled).is_err());
        let relabeled = BoundCredentials {
            nonce: Nonce::random(),
            ..creds.clone()
        };
        assert!(verifier.verify(&request, &relabeled).is_err());

        // A small-order ephemeral key is refused at parse.
        let weak = RequestVerifier::from_be_bytes({
            let mut identity = [0u8; 32];
            identity[0] = 1;
            identity
        });
        assert!(matches!(
            weak.verify(&request, &creds).unwrap_err(),
            AuthnError::InvalidKey
        ));
    }

    #[test]
    fn seq_windows() {
        let mut window = SeqWindow::default();
        assert!(window.spend(1));
        assert!(!window.spend(1));
        assert!(window.spend(5));
        assert!(window.spend(3)); // out of order is fine
        assert!(!window.spend(3)); // replay is not
        assert!(!window.spend(5));
        assert!(window.spend(100)); // ages the bits across a word
        assert!(!window.spend(5)); // still spent
        assert!(window.spend(4)); // still spendable
        assert!(window.spend(300));
        assert!(window.spend(45)); // the oldest tracked (300 - 255)
        assert!(!window.spend(44)); // one older: refused, spent or not
        assert!(!window.spend(100)); // still spent, mid-window
        assert!(window.spend(2_000));
        assert!(!window.spend(300));
    }

    #[test]
    fn authn_errors() {
        assert!(matches!(
            Credentials::from_str("").unwrap_err(),
            AuthnError::MissingScheme
        ));
        assert!(matches!(
            Credentials::from_str("Foo foo").unwrap_err(),
            AuthnError::InvalidScheme(scheme) if scheme == "Foo"
        ));
        assert!(matches!(
            Credentials::from_str("Sush foo").unwrap_err(),
            AuthnError::InvalidParam
        ));
        assert!(matches!(
            Credentials::from_str("Sush x=y,z").unwrap_err(),
            AuthnError::InvalidParam
        ));
        assert!(matches!(
            Credentials::from_str("Sush x=y,x=z").unwrap_err(),
            AuthnError::DuplicateParam(p) if p == "x"
        ));
        assert!(matches!(
            Credentials::from_str("Sush x=y").unwrap_err(),
            AuthnError::MissingParam(p) if p == "nonce"
        ));
        assert!(matches!(
            Credentials::from_str("Sush nonce=abandon").unwrap_err(),
            AuthnError::MissingParam(p) if p == "cnonce"
        ));
        let epk = RequestKey::new().verifier();
        assert!(matches!(
            Credentials::from_str(
                "Sush nonce=abandon,cnonce=ability,key-id=able,epk=plugh,r=burger,s=burst,flags=0,counter=0"
            )
            .unwrap_err(),
            AuthnError::InvalidParam
        ));
        assert!(matches!(
            Credentials::from_str(&format!(
                "Sush nonce=abandon,cnonce=ability,key-id=able,epk={epk},r=burger,s=burst,flags=0,counter=foo"
            ))
            .unwrap_err(),
            AuthnError::InvalidParam
        ));
        assert!(matches!(
            Credentials::from_str(&format!(
                "Sush nonce=abandon,cnonce=ability,key-id=able,epk={epk},r=burger,s=burst,flags=0,counter=0,foo=bar"
            ))
            .unwrap_err(),
            AuthnError::TooManyParams
        ));
    }
}
