pub mod certs;
pub mod codephrases;
pub mod jobs;
pub mod wordlist;

/// The file name of the OpenAPI document generated by
/// [Dropshot](https://crates.io/crates/dropshot) and used by
/// [Progenitor](https://crates.io/crates/progenitor).
pub const OPENAPI_DOCUMENT: &str = "sush.json";
pub const OPENAPI_TITLE: &str = "Oxide Support Shell";
pub const OPENAPI_VERSION: &str = "0.1.0";
