[package]
name = "sush-api"
description = "Oxide Support Shell HTTP API"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
borsh.workspace = true
chrono.workspace = true
dropshot.workspace = true
http-range-header.workspace = true
hyper.workspace = true
schemars.workspace = true
serde.workspace = true
sled-hardware-types.workspace = true
sush-common = { path = "../common" }
thiserror.workspace = true
