name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-22.04-8core
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.91
        components: clippy,rustfmt

    - name: Checkout
      uses: actions/checkout@v6

    - name: Get token to fetch private repositories
      uses: oxidecomputer/oidcx-action@main
      with:
        service: github
        repositories: oxidecomputer/permission-slip
        permissions: contents:read
        configure-git: true

    - name: Lint
      run: |
        cargo fmt -- --check &&
        cargo clippy -- --no-deps --deny warnings &&
        cargo clippy --tests -- --no-deps --deny warnings &&
        cargo clippy --package sush-client --features permslip -- --no-deps --deny warnings

    - name: Build
      run: |
        cargo build --locked &&
        cargo build --locked --package sush-client --features permslip

    - name: Test
      run: cargo test
